// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 1. Najpierw szukamy połączenia bezpośredniego do migracji (NON_POOLING)
    // 2. Jako fallback używamy głównego linku PRISMA_URL
    url: process.env["POSTGRES_URL_NON_POOLING"] || process.env["POSTGRES_PRISMA_URL"],
  },
});