// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Dla procesów migracji/push Prisma 7 potrzebuje bezpośredniego połączenia (DIRECT_URL)
    // Jeśli go nie ma, użyje głównego POSTGRES_URL
    url: process.env["DIRECT_URL"] || process.env["POSTGRES_URL"],
  },
});